# Copyright (c) 2022 Jaehong Kang
# Licensed under Apache License v2.0

name: Unit Tests

on:
  push:
    paths:
      - '.github/workflows/unit-tests.yml'
      - 'swift.sh'
      - 'unit-tests/**/*'
  pull_request:
    paths-ignore:
      - '.github/workflows/unit-tests.yml'
      - 'swift.sh'
      - 'unit-tests/**/*'

jobs:
  warning:
    name: Warning
    strategy:
      fail-fast: true
      matrix:
        operating-system: ["ubuntu-latest"]
        swift-version: ["5.4.3", "5.5.3", "5.6.2"]
        include:
          - operating-system: "macos-12"
            swift-version: "5.6.2"
            xcode-version: "13.4.1"
          - operating-system: "macos-12"
            swift-version: "5.5.3"
            xcode-version: "13.2.1"
          - operating-system: "macos-11"
            swift-version: "5.4.3"
            xcode-version: "12.5.1"
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v3
      - uses: sinoru/actions-setup-xcode@v2
        if: ${{ startsWith(runner.os, 'macOS') && matrix.xcode-version }}
        with:
          xcode-version: ${{ matrix.xcode-version }}
          apple-id: ${{ secrets.APPLE_ID }}
          apple-id-password: ${{ secrets.APPLE_ID_PASSWORD }}
      - uses: sinoru/actions-setup-swift@v2
        with:
          swift-version: ${{ matrix.swift-version }}
      - run: diff <(swift build --package-path test --product Warning) unit-tests/warning-expected.txt
